### ISSUE TITLE
Lots of errors with DNN 9.4.2

### ISSUE THREAD

**Issue by b-creative** [ventrian/News-Articles#42]
aiaiai, does anyone have any idea? 

Just installed DNN 9.4.2

Lots of errors start **with LatestArticles:**

```
ModuleControlSource:DesktopModules/DnnForge - LatestArticles/LatestArticles.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1900b8b2-2098-4dec-a598-2fe409645239
AssemblyVersion:9.4.2
PortalId:4
UserId:-1
TabId:750
RawUrl:/
Referrer:
UserAgent:
ExceptionHash:QXh2ZYH7BvTojTaO0TWPYCkl4Ck=
Message:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.
StackTrace:
InnerMessage:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

InnerStackTrace:

   at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID)
   at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle)
   at Ventrian.NewsArticles.LatestArticles.rptLatestArticles_OnItemDataBound(Object sender, RepeaterItemEventArgs e)
```

and with **News Articles:**

```
ModuleControlSource:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:49525813-d0f4-4663-85e0-12f29ddd6871
AssemblyVersion:9.4.2
PortalId:4
UserId:1
TabId:755
RawUrl:/pagename?SkinSrc=/portals/_default/skins/_default/no%20skin

Referrer:
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

ExceptionHash:JV+YMttUJ0PbEf+7iMo0mu4G7pk=
Message:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

StackTrace:
InnerMessage:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

InnerStackTrace:
   at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID)
   at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle)
   at Ventrian.NewsArticles.Controls.Listing.rptListing_OnItemDataBound(Object sender, RepeaterItemEventArgs e)
```

**Comment by Scippy** [comment]
The same occur with Property Agent, I’ve released on scippy fork a new PA version that work fine on DNN 9.3.2 but with DNN 9.4.x a lot of errors occur.
Compiling the project on Visual Studio with the latest DNN Dll’s referenced I get a lot of errors, if I open this errors one by one they disappear and Visual Studio seems he resolves them but if I try to recompile they reappear!
Any Idea where is the break point and how to solve this?

**Comment by bdukes** [comment]
To compile for 9.4.2, you need to add a reference to DotNetNuke.Abstractions and then you should be able to recompile.  That said, we're looking at reverting this change in 9.4.3 so you may want to wait on that if you can.

**Comment by Scippy** [comment]
I've tried to compile using latest 9.4.3 but I receive still a lot of errors! With DNN 9.2.1 all work fine.
I'm tring this with PA https://github.com/Scippy/Property-Agent/tree/DNN9-Update
Any idea how to fix?
Thanks!

**Comment by bdukes** [comment]
What sorts of errors are you seeing @Scippy?  You've replaced `DotNetNuke.dll` with the version that's in the [RC package](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.4.3-rc1)?

I had tested that News Articles compiles and runs fine on 9.4.3, but haven't looked at Property Agent…

**Comment by Scippy** [comment]
Hi Dukes, thanks for your reply.
Yes, I've only replaced the Dotnetnuke.dll and DotNetNuke.Web.Client.dll with those in this [RC package](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.4.3-rc1)
It is difficult to tell you the errors because they are many and of various types ... over two hundred. Everything works ok with Dotnetnuke.dll and DotNetNuke.Web.Client.dll up to the DNN version 9.2.1
If you had the chance to try remember to use my branch DNN9-Update that you can find [here](https://github.com/Scippy/Property-Agent/tree/DNN9-Update).
Very thanks

**Comment by bdukes** [comment]
I think the piece that you may be missing is that some of the referenced types moved into `DotNetNuke.Abstractions.dll`.  If you add a reference to that, does it fix any of the compile errors?

**Comment by Scippy** [comment]
I've tried to add also DotNetNuke.Abstractions.dll but nothing change, 212 errors before and after

**Comment by salemkh** [comment]
Indeed when I upgraded to 9.4.2 I the module broke with errors


ExceptionHash:JV+YMttUJ0PbEf+7iMo0mu4G7pk=

Message:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

StackTrace:

InnerMessage:Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'.

InnerStackTrace:

   at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID)
   at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle)
   at Ventrian.NewsArticles.Controls.Listing.rptListing_OnItemDataBound(Object sender, RepeaterItemEventArgs e)


and on the module itself, the following:


An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID) at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle) at Ventrian.NewsArticles.Controls.Listing.rptListing_OnItemDataBound(Object sender, RepeaterItemEventArgs e) --- End of inner exception stack trace ---
An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID) at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle) at Ventrian.NewsArticles.Controls.Listing.rptListing_OnItemDataBound(Object sender, RepeaterItemEventArgs e) --- End of inner exception stack trace ---
An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Common.Globals.FriendlyUrl(DotNetNuke.Entities.Tabs.TabInfo, System.String, System.String, DotNetNuke.Entities.Portals.PortalSettings)'. at Ventrian.NewsArticles.Common.GetArticleLink(ArticleInfo objArticle, TabInfo objTab, ArticleSettings articleSettings, Boolean includeCategory, Int32 pageID) at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle) at Ventrian.NewsArticles.Controls.Listing.rptListing_OnItemDataBound(Object sender, RepeaterItemEventArgs e) --- End of inner exception stack trace ---

**Comment by b-creative** [comment]
Should be resolved: https://github.com/dnnsoftware/Dnn.Platform/releases/latest

**Comment by Scippy** [comment]
Still nothing to do...I've tried also with latest [DNN 9.4.3 release](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.4.3) and all errors are still there!
It look like that in these latest DNN releases there are a lot regression issue that make no longer work many modules.

**Comment by bdukes** [comment]
You're seeing runtime errors after upgrading to 9.4.3, with the official release that was compiled against an older version of DNN?  Or are you saying that you're having compile errors trying to compile (News Articles or Property Agent?) against the 9.4.3 DLLs?

**Comment by bdukes** [comment]
@Scippy I submitted a pull request Scippy/Property-Agent#1 with the changes I made to support compiling the PA source against DNN 9.4.3.

If there are other specific errors you're still running into, please let us know.  Hope it helps!

**Comment by Scippy** [comment]
Many Thanks Brian for your pull request but after accepted and updated my local project with your pull the errors are still there!
You're instead able to compile? After your pull I need always to regress the DLLs at least up to the DNN version 9.2 to make the project compilable again! this is getting me frustrating...

**Comment by bdukes** [comment]
What version of Visual Studio are you using?  Can you post the build output?

**Comment by Scippy** [comment]
I'm using VisualStudio2017
Errors list [HERE](https://www.dropbox.com/s/f56jjr0e0czntjp/ErrorList.txt?dl=0)
Build Output [HERE](https://www.dropbox.com/s/1v1os3ab8w99o4f/BuildOutput.txt?dl=0)

**Comment by bdukes** [comment]
My PR changed the framework version of the projects to .NET 4.7.2 (since that's what DNN 9.4.x is targeting).  But your build output starts by saying
>warning MSB3274: The primary reference "DotNetNuke, Version=9.4.3.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".

So I think your Visual Studio doesn't have support for building against .NET 4.7.2.  Try installing the Developer Pack from https://dotnet.microsoft.com/download/dotnet-framework/net472 and see if that helps.  Alternatively, I believe Visual Studio 2019 supports .NET 4.7.2 out of the box

**Comment by Scippy** [comment]
Yess! That's the problem!
Very very thanks Dukes!
